# iot-pipeline/mosquitto/config/mosquitto.conf
listener 1883
listener 9001
protocol websockets

# Pour le TP, on laisse anonyme. Mais le projet demande l'authentification.
# On va l'ajouter plus tard dans la partie avancée.
allow_anonymous true

log_type all
log_dest stdout